const CONFIG = {
    introTitle: 'helu babeee',
    introDesc: `Em có điều này muốn hỏi anhhh, hãy trả lời thật lòng nhé`,
    btnIntro: 'Ok nè',
    title: 'Anh có yêu em khônggg?',
    desc: 'Nếu anh không trả lời mà thoát ra thì tức là chồng em nhé :))',
    btnYes: 'Coá, anh yêu em vlll :3 ',
    btnNo: 'Không, em bị ngáo à?',
    question:'Trên thế giới hơn 7 tỉ người mà sao anh lại yêu em?',
    btnReply: 'Gửi cho emm <3',
    reply: 'Tại em xinh xinh xinh vl',
    mess: 'Em biết anh yêu em mà :))',
    messDesc: 'Mãi iu anhhh hihii',
    btnAccept: 'Okiiiii yêu em <3',
    messLink: 'gamevuicuanguyenphuonganhxinhdep}
